define({
  root: ({
      _widgetLabel: "Add Data",
      addFromPortal: "Add from Portal",
      addFromWeb: "Add from Web",
      addFromServer: "Add from Server",
      addFromFile: "Add from File",
      addFromPortalAndServer:"Add from Portal & Server",
      withinMapArea: "Within Map Area",
      type: "Type",
      browse: "Browse",
      layerAdd: "Add",
      layerRemove: "Remove",
      layerRequest:"Request",
      resultsFound: "results found.",
      serviceURL: "URL",
      search: "Go",
      close:"Close",
      useAsBasemap: "Use as Basemap",
      addDataPortalDescription: "Enter a keyword to discover spatial data. Click 'Add' to the data on the map. Once added you can remove data by clicking 'Remove'."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 1
});
